#!/usr/bin/env python3

import os
import time

TRIGGER_NODE = "/sys/devices/platform/leds/leds/PWR/trigger"
BRIGHTNESS_NODE = "/sys/devices/platform/leds/leds/PWR/brightness"

while True:
    if os.path.isfile(TRIGGER_NODE) and os.path.isfile(BRIGHTNESS_NODE):
        break
    time.sleep(1)

with open(TRIGGER_NODE, "wb") as f:
    f.write(b"none\n")

with open(BRIGHTNESS_NODE, "wb") as f:
    while True:
        f.write(b"1")
        f.seek(0)
        time.sleep(0.005)
        f.write(b"0")
        f.seek(0)
        time.sleep(2)

