#!/bin/bash

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

cd ${HOME}
while [ true ]; do
    flutter-pi --release ${HOME}/flutter_assets
    sleep 1
done

