#!/usr/bin/env python3

import os
import random
import time
import subprocess

def sleep_random(min_sec, max_sec):
    sleep_seconds = random.uniform(min_sec, max_sec)
    print(f"Sleeping for {sleep_seconds} seconds")
    time.sleep(sleep_seconds)

os.chdir(os.environ.get("HOME"))
sleep_random(10, 60)

while True:
    rclone_ret = subprocess.run(["rclone", "sync", "-v", "signage-slides:./", "./signage-slides-tmp/"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if rclone_ret.returncode != 0:
        print(rclone_ret.stdout)
        print(rclone_ret.stderr)
        print("Failed to sync from WebDAV server")
    else:
        diff_ret = subprocess.run(["diff", "-r", "./signage-slides-tmp/", "./signage-slides/"])
        if diff_ret.returncode != 0:
            print("Content changed, sync direcotry and restart flutter application")
            subprocess.run(["rsync", "-av", "--delete", "./signage-slides-tmp/", "./signage-slides/"])
            subprocess.run(["killall", "flutter-pi"])
        else:
            print("Directory content are the same")

    sleep_random(30, 60)

